base_config: "configs/base.yaml"
experiment_name: "Hybrid_Alpha_Expression"
strategy:
  module: src.backtest.strategies.formula
  class: FormulaStrategy
  params:
    expressions:
      # - "if_else(ts_rank(ts_return(FD_Close, 21), 252) > 0.7, -ts_rank(ts_variance(FD_Close, 21), 252), 0)"
      - "ts_backfill(if_else(ts_rank(ts_skewness(FD_Close, 21), 126) > 0.9, 1, 0), 252)"
      # - "if_else(ts_rank(ts_variance(ts_return(FD_Close, 1), 21), 126) > 0.8, 1, -1)"
      # - "0"
