base_config: "configs/base.yaml"
experiment_name: "Hybrid_Alpha_Expression"
strategy:
  module: src.backtest.strategies.formula
  class: FormulaStrategy
  params:
    expressions:
      # - "ret = ts_return(FD_Close, 1); alpha=if_else(ts_rank(ts_variance(ret, 21), 126) > 0.8, rank(ret), -1); alpha"
      - "x=ts_backfill(ts2vec_manifold_0, 252); y=ts_backfill(ts2vec_manifold_1, 252); ts_corr(x, y, 126)"
