base_config: "configs/base.yaml"
experiment_name: "Hybrid_Alpha_Expression"
strategy:
  module: src.backtest.strategies.formula
  class: FormulaStrategy
  params:
    top_n: 5
    expressions:
      # - "vector_proj(rank(ts2vec_manifold_0), rank(ts2vec_manifold_1))"
      # - "ts_zscore(ts_corr(ts2vec_manifold_0, ts2vec_manifold_1, 63), 252)"
      # - "ts_skewness(ts_return(FD_Close, 1), 21)"
      - "if_else(ts_rank(ts_return(FD_Close, 5), 252) > 0.7, -ts_rank(ts_volatility(FD_Close, 21), 252), ts_rank(ts_momentum(FD_Close, 10), 252))"